"""
Django settings for phishing_project.
Generated by developer AI pipeline assistant.
"""

from pathlib import Path
import os

# 1. Base Directory Path Resolution
# Resolves the absolute path to your root workspace folder automatically
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Core Security Configurations
# Dev Warning: Keep the secret key secret in production!
SECRET_KEY = 'django-insecure-local-dev-fallback-key-change-this-in-prod'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Domains/IPs allowed to host or connect to this backend service
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# 3. Application Definitions & Registrations
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Your custom application module handling threat detection and dashboards
    'detector',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Security check blocking form forgery
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Path to the primary root URL router mapping engine
ROOT_URLCONF = 'phishing_project.urls'

# 4. User Interface Presentation Rendering Engine
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Tells Django to look globally for templates if configured, but we isolate in apps
        'DIRS': [],
        'APP_DIRS': True, # Crucial: Enables automatic searching inside /templates/ directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Gateway application module to pass live network execution
WSGI_APPLICATION = 'phishing_project.wsgi'

# 5. Database Relational Management Schema Configuration
# Using SQLite locally out-of-the-box for seamless setup tracking scan history logs
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 6. Password Validation Security Rules
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 7. Localization Settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# 8. Static Web Assets Files Delivery Controls (CSS, JS, Visual Graphics)
STATIC_URL = 'static/'
# This maps our project structure to fetch shared stylesheet and javascript libraries
STATICFILES_DIRS = [
    BASE_DIR / "detector" / "static",
]

# 9. Autofield Auto Incrementor Type Mapping 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
